### ISSUE TITLE
BossCraft - General Development Library for BossPVP

### ISSUE THREAD

**Issue by SzymonDziak** [BossPVP-Company/BossCraft#3]
**All related planning and documentation**

> 

- [ ] Create task board for improvements, wants & needs. 
- [ ] Create standard documentation & pull request strategy. 
- [ ] Add UPDATES.md - log file for incremental changes and sprints.
Example:
```
05/17/2023:
- Created Github Issue #3 for general todos 

05/15/2023:
- Officially beginning work
```
- [ ] Open Source the project

Please add comments below and we will create a continuous log.

**Comment by SzymonDziak** [comment]
@Phoenix-Ra

**Comment by Phoenix-Ra** [comment]
In Progress:
 - config lib update to add config categories feature( replacement of eco stuff )

**Comment by Phoenix-Ra** [comment]
Libreforge completed version(task list is not full):
 - [ ] first version
 - [ ] improvement of the lib structure (to not to have it like kotlin but in java)
 - [ ] rework of placeholders (PlaceholdersAPI cannot replace the eco's placeholders used in libreforge)
 - [ ] add minor features that wasn't added for a first version(mutators, filters etc)
 - [ ] add all effect types from libreforge
 - [ ] add all trigger types from libreforge
 - [ ] add all condition types from libreforge
 - [ ] add all types for minor features(mutators, filters etc) from libreforge
 - [ ] Java docs
